export const riddleList = [
  "I bought beer here for generations until a continent's shared dream made me worthless in 2002. Find the money they spent before the change, with a king still on my face.",
  "The famous weeing boy has a lesser-known companion who cocks his leg instead \u2014 a bronze mongrel caught mid-relief down a quiet lane.",
  "Spun by hand into impossibly fine patterns, this thread-work shares the city's name and once dressed royalty.",
  "An anonymous stencil artist never agreed to it, yet a whole museum of his recreated work stands here \u2014 bring back proof from inside.",
  "I throw a flame and slip into a pocket, dressed up in this country's three colours for a tourist to take home.",
  "Three apples high, blue of skin, dreamed up by a Belgian called Peyo, and living in a mushroom.",
  "A ginger maestro from a village near Ghent, his passes slice defences in two \u2014 find his name or his face.",
  "Once the jewel of Chelsea and Madrid, this countryman's surname is itself a word for danger.",
  "Cloudy, pale, and spiced with coriander and orange peel, this wheat beer hails from a village most Brits can't pronounce.",
  "Knocked flat only to stand again, I wear a red stripe at the throat and always come in tens.",
  "Robed monks gave their abbey's name to this golden ale, served reverently in a footed chalice on every caf\u00e9 table.",
  "A premier statesman shares my name, though I never grew from his soil. Boil me too long and I'll clear a room faster than any scandal \u2014 yet I claim this city as my own.",
  "I am a battlefield grid you devour. Two cities claim my parentage \u2014 one gives me air and face-thin edges, the other buries me in pearls that crack between your teeth.",
  "Five centuries of stage fright and never once stopped performing. I own a wardrobe a thousand strong, dress as Elvis and Dracula by turns, yet wear nothing at all when the tourists arrive.",
  "A monk's cocoa experiment in 1912 gave the world a filled shell with a French name meaning 'praised.' Find me ribboned, regimented, and arranged in rows.",
  "Read me from the staff outward: the colour of coal, the colour of greed, the colour of a wound. Three bars, and Napoleon's defeat happened on my soil.",
  "A painter's daughter lent me her name and her face in Leuven. 'Reassuringly expensive,' a clever ad once lied, though I'm the cheapest thing on most British shelves.",
  "Pull me on and you answer to a hellish name earned in 1906. But shed the horns and the colour, and I'm just cloth \u2014 find me crimson, and find me sporting.",
  "A century ago a Dutch newspaperman damned this team to the underworld with one phrase. Now the fiend grins from scarves and stickers \u2014 anything but a shirt.",
  "This nation crowned a Ninth Art beside painting and dance. Bring me bound panels and bubbled speech \u2014 Herg\u00e9's whole trade in your hands.",
  "Herg\u00e9's quiffed creation and his terrier are pinned three storeys up, mid-stride forever, on a gable in the Marolles' shadow.",
  "A Romantic exile crowned this square the loveliest on earth. Guildhalls drip gold around a tower where, every other August, a carpet of begonias is laid.",
  "Nine iron worlds magnify a single crystal of metal 165 billion times, a relic of a fair that promised the atomic future. Stand before the giant himself \u2014 no keyring will do.",
  "A monument to the atom, blown up to absurdity for a '58 fair, now shrinks to fit a fridge or a keyring. Bring me the trinket, never the titan.",
  "Drink your way through my whole roster and you'd need a new liver and a record book. My patron beast is pink, and only the truly far-gone ever meet him."
];
